### ISSUE TITLE
default partition

### ISSUE THREAD

**Issue by tentrillion** [vsoch/forward#1]
**Feature request:** I'm a Sherlock nube but was immediately drawn to this repo because I use Jupyter a lot.  I got Jupyter working on Sherlock by using these scripts, which is awesome.  (Thank you!)  The only real hiccup was that it took me a long time to find out that I should set my default partition to `normal`, instead of `rdror` or `drorlab` or whatever the default value is.  Would there be a way to change the default, or at least print out that `normal` is an option for users whose PIs don't buy a dedicated partition?

(A more correct view of my issue may be that the problem is with Sherlock documentation instead of this repo but I figured I would start here first.)

**Comment by raphtown** [comment]
Hey tentrillion, thank you for the message and glad to hear it worked for you!  I went ahead and clarified the setup script, as well as switched the default partition to normal.

**Comment by tentrillion** [comment]
https://github.com/drorlab/forward/commit/f6951a4c4ab8f2ed4fe711bbfef7ab1b36316051
