### ISSUE TITLE
Running a notebook: "ssh: Could not resolve hostname"

### ISSUE THREAD

**Issue by royzawadzki** [vsoch/forward#19]
I have followed all the steps detailed [here](https://vsoch.github.io/lessons/sherlock-jupyter/). When I get to the step where you start a notebook using `bash start.sh jupyter /path/to/dir` it doesn't connect, giving me a notice that it "could not resolve hostname." Here's what I'm running and the output (for context my SUNetID is rzawadzk):

```
DN52ekoj:forward royzawadzki$ bash start.sh sherlock/py3-jupyter ../BPA
== Finding Script ==
Looking for sbatches/rzawadzk/sherlock/py3-jupyter.sbatch
Looking for sbatches/sherlock/py3-jupyter.sbatch
Script      sbatches/sherlock/py3-jupyter.sbatch

== Checking for previous notebook ==
ssh: Could not resolve hostname rzawadzk: nodename nor servname provided, or not known
No existing sherlock/py3-jupyter jobs found, continuing...

== Getting destination directory ==
ssh: Could not resolve hostname rzawadzk: nodename nor servname provided, or not known
ssh: Could not resolve hostname rzawadzk: nodename nor servname provided, or not known

== Uploading sbatch script ==
ssh: Could not resolve hostname rzawadzk: nodename nor servname provided, or not known
lost connection

== Submitting sbatch ==
rzawadzk sbatch --job-name=sherlock/py3-jupyter --partition=normal --output=/forward-util/py3-jupyter.sbatch.out --error=/forward-util/py3-jupyter.sbatch.err --mem=20G --time=8:00:00 /forward-util/py3-jupyter.sbatch 59258 "../BPA"
ssh: Could not resolve hostname rzawadzk: nodename nor servname provided, or not known

== View logs in separate terminal ==
ssh rzawadzk cat /forward-util/py3-jupyter.sbatch.out
ssh rzawadzk cat /forward-util/py3-jupyter.sbatch.err

== Waiting for job to start, using exponential backoff ==
ssh: Could not resolve hostname rzawadzk: nodename nor servname provided, or not known
Attempt 0: not ready yet... retrying in 1..
ssh: Could not resolve hostname rzawadzk: nodename nor servname provided, or not known
Attempt 1: not ready yet... retrying in 2..
ssh: Could not resolve hostname rzawadzk: nodename nor servname provided, or not known
Attempt 2: not ready yet... retrying in 4..
```

And so on with the attempts. I'm not sure what's going on here.

**Comment by vsoch** [comment]
hey @royzawadzki ! I'm actually putting in a bunch of changes (and as bad luck would have it you are using one of the scripts that I haven't updated yet). Could you tell me what you are trying to do so I can give you the updated usage? And please show me:

 - your params.sh? 
 - the .out and .err logs in the forward-util folder in your $HOME directory (on sherlock?)

**Comment by vsoch** [comment]
I think your params.sh is missing the RESOURCE variable, which should be sherlock, try moving the old version somewhere for backing, running the setup.sh again and compare the two.

**Comment by royzawadzki** [comment]
@vsoch that was exactly it, I went back and redefined the RESOURCE variable to be `sherlock`. Thanks for the help!
