### ISSUE TITLE
resource for sherlock!

### ISSUE THREAD

**Issue by vsoch** [vsoch/forward#2]
hey @raphtown ! I saw your email on the list, and wanted to say how great this is. This is a really cool resource, and I'd like to propose that I can test it out (notice I'm part of Research Computing at Stanford!) and then write up a little instructional on our [lessons page](http://vsoch.github.io/lessons). I'm thinking I might be able to containerize some of the steps to make it easier, but I haven't given it a try yet. If we are able to get everything working, I can PR to this repo with updates, and then do a little writeup (and I'd ask for your contribution if you are willing!) Let me know your thoughts - looking forward to trying it out.

**Comment by raphtown** [comment]
Hello vsoch!

I would be happy for you to test it all out/write out instructions on your lessons page.  And yes, parts of the process (especially the setup) could be made more straightforward, so if you have a PR with updates it would definitely be appreciated!

I'll keep this issue open for now so we can discuss as needed.

Raphael.

**Comment by vsoch** [comment]
I think we are good here, thanks for the help with this @raphtown !
