### ISSUE TITLE
open source license

### ISSUE THREAD

**Issue by vsoch** [vsoch/forward#3]
I would like to suggest adding an open source license (MIT or BSD3, or something in the GPL family) before we open this up to contributions from others (and myself!) Here are a list of options --> https://opensource.org/licenses. If you let me know which is your preference, I'd be glad to add in a PR.

**Comment by raphtown** [comment]
Let's do the MIT license.  Thanks again for helping with all this!

**Comment by vsoch** [comment]
okay done!

yeah I'm working on it this morning! Having fun so far :)
