### ISSUE TITLE
Trouble logging in to launch jupyter notebook

### ISSUE THREAD

**Issue by isabellow** [vsoch/forward#30]
Hi,

I'm attempting to run a jupyter notebook through sherlock on my local machine (Windows 10), following the instructions here:
[https://vsoch.github.io/lessons/sherlock-jupyter/](https://vsoch.github.io/lessons/sherlock-jupyter/)

I believe that I have successfully cloned the forward repo, generated the parameters file, and created the ssh credentials (all on my local computer). I then ran into a couple issues:

**1. Issue creating password for jupyter notebook**
I tried to create a password for the notebook using the following code from the $HOME folder:
```
$ sdev
$ ml python/3.6.1
$ ml py-jupyter/1.0.0_py36
$ which jupyter /share/software/user/open/py-jupyter/1.0.0_py36/bin/jupyter
$ jupyter notebook password
```
which resulted in the following error message:
```
$ which jupyter /share/software/user/open/py-jupyter/1.0.0_py36/bin/jupyter
/share/software/user/open/py-jupyter/1.0.0_py36/bin/jupyter
/share/software/user/open/py-jupyter/1.0.0_py36/bin/jupyter
$ jupyter notebook password
Enter password:
Verify password:
Traceback (most recent call last):
  File "/share/software/user/open/py-jupyter/1.0.0_py36/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/share/software/user/open/py-jupyter/1.0.0_py36/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/share/software/user/open/py-jupyter/1.0.0_py36/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/share/software/user/open/py-jupyter/1.0.0_py36/lib/python3.6/site-packages/notebook/notebookapp.py", line 1362, in start
    super(NotebookApp, self).start()
  File "/share/software/user/open/py-jupyter/1.0.0_py36/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/share/software/user/open/py-jupyter/1.0.0_py36/lib/python3.6/site-packages/notebook/notebookapp.py", line 345, in start
    set_password(config_file=self.config_file)
  File "/share/software/user/open/py-jupyter/1.0.0_py36/lib/python3.6/site-packages/notebook/auth/security.py", line 148, in set_password
    config.NotebookApp.password = hashed_password
  File "/share/software/user/open/python/3.6.1/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/share/software/user/open/py-jupyter/1.0.0_py36/lib/python3.6/site-packages/notebook/auth/security.py", line 131, in persist_config
    with io.open(config_file, 'w', encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/users/ilow/.jupyter/jupyter_notebook_config.json'
```
I was able to get around this issue (I think) with the following:
`$ mkdir ~/.jupyter`

**2. Issue logging in to launch notebook**
I next tried to launch a notebook, following the instructions in Part 3 of the above tutorial:
`$ bash start.sh py3-jupyter /home/users/ilow`
which resulted in a strange loop where I kept entering my password, 2-factor authenticating, and then it would ask for my password/2FA again:
```
== Finding Script ==
Looking for sbatches/sherlock/py3-jupyter.sbatch
Script      sbatches/sherlock/py3-jupyter.sbatch

== Checking for previous notebook ==
mux_client_request_session: read from master failed: Connection reset by peer
ilow@sh-ln06.stanford.edu's password:
Duo two-factor login for ilow

Enter a passcode or select one of the following options:

 1. Duo Push to XXX-XXX-5751
 2. Phone call to XXX-XXX-5751
 3. SMS passcodes to XXX-XXX-5751

Passcode or option (1-3): 1
ControlSocket /c/Users/ilow1/.ssh/DESKTOP-0INRECLilow@sh-ln06.stanford.edu:22 already exists, disabling multiplexing
No existing py3-jupyter jobs found, continuing...

== Getting destination directory ==
mux_client_request_session: read from master failed: Connection reset by peer
ilow@sh-ln06.stanford.edu's password:
```

Any idea why this would happen or how to remedy? I'm new to Sherlock and any advice would be much appreciated! Thanks!

**Comment by vsoch** [comment]
hey @isabellow ! We could spend the time to debug (harder on Windows) but instead I'd like to suggest that you check out Sherlock on demand :point_right:  https://www.sherlock.stanford.edu/docs/user-guide/ondemand/ 

The forward tool was created before OnDemand was available, and since it's browser based it works much better. Please give it a try and let me know if it works for you!

**Comment by isabellow** [comment]
For some reason OnDemand wasn't working for me this morning--but it seemed to do the trick now. Thank you!

**Comment by vsoch** [comment]
Awesome! Glad to hear. Yes I do believe there were some issues earlier today, glad it's working again.
