### ISSUE TITLE
ControlPath can be too long

### ISSUE THREAD

**Issue by neutrinonerd3333** [vsoch/forward#31]
I've was using forward to run Jupyter notebooks on Sherlock, using the default ssh config in `hosts/sherlock_ssh.sh`, and recently encountered an SSH Error: `ControlPath too long`.

I discovered that it was because the default ssh config includes the full hostname in the ControlPath for the Sherlock connection. I was at SLAC, and the hostname my machine was assigned was surprisingly long. I fixed this by replacing the ControlPath name `%l%r@%h:%p` with `%C`, which gives a hash of `%l%h%p%r` (see `ssh_config` manpage).

(So… pr maybe?)

**Comment by vsoch** [comment]
Yes, it would be greatly appreciated! And you can get a point for Hacktoberfest 🎃
