### ISSUE TITLE
USERNAME variable not changing

### ISSUE THREAD

**Issue by depond1** [vsoch/forward#35]
Hi, when attempting a log in to a Sherlock node it seems to be using my local USERNAME instead of the one initialized in the params.sh file. Im on Mac OS Catalina 10.15, I tried editing the start.sh file to hard code in my Sherlock username but it still is referencing my local USERNAME

**Comment by vsoch** [comment]
Can you give me an example to reproduce your issue? If you need to refer to your username in the job submission script, since it's run when it's already on the node you can just refer to `$USER`.

**Comment by depond1** [comment]
Okay so I have it partially figured out...I was using this config text before:
Host login.sherlock.stanford.edu
    ControlMaster auto
    ControlPersist yes
    ControlPath ~/.ssh/%l%r@%h:%p%

and changed to this

Host sherlock
    User **myusername**
    Hostname sh02-ln01.stanford.edu
    GSSAPIDelegateCredentials yes
    GSSAPIAuthentication yes
    ControlMaster auto
    ControlPersist yes
    ControlPath ~/.ssh/%l%r@%h:%p

and the error is gone on my old laptop macOS High Sierra 10.13.6 but still persists on my OS Catalina laptop

**Comment by depond1** [comment]
its using my local username when accessing the function check_previous_submit()
so when logging in to ssh it shows this:

== Checking for previous notebook ==
phildepond@sherlock.stanford.edu's password:

**Comment by vsoch** [comment]
Ah, is it the case that Macs have a $USERNAME defined, regardless of any external tool like sherlock? if so, that's the bug - the $USERNAME being used there isn't the one defined by forward, but by your Mac. Could you open a new terminal and check this variable?

**Comment by depond1** [comment]
Perhaps in the new os! when I echo $USERNAME it shows my local username

**Comment by vsoch** [comment]
Yep, that's the issue! Let me open a PR that updates the variables to be namespaced with `FORWARD_`. I usually do this for most tools that need some namespace in their environment, but didn't here. Give me a few minutes!

**Comment by depond1** [comment]
thank you so much!

**Comment by vsoch** [comment]
@depond1 would you care to test this pull request branch?

https://github.com/vsoch/forward/pull/36

You should be able to clone the branch to a new folder

```bash
git clone -b update/environment-namespace git@github.com:vsoch/forward.git
git clone -b update/environment-namespace https://github.com/vsoch/forward
```
and then run ./setup.sh to produce the params.sh and proceed as before. Let me know if anything is not working!

**Comment by depond1** [comment]
I am getting a permissions error I believe,

Cloning into 'forward'...
Warning: Permanently added the RSA host key for IP address '192.30.255.112' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by vsoch** [comment]
Ah that just means that you don't have ssl configured, in which case the second command is what you want :)

```bash
git clone -b update/environment-namespace https://github.com/vsoch/forward
```
I would highly recommend adding an ssh key to your account if you haven't already, and 2FA too. here are instructions for the first: https://help.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account

**Comment by depond1** [comment]
thanks! looks like it works! :) I needed to update the end.sh script to include $FORWARD_USERNAME as well

**Comment by vsoch** [comment]
That would be a bug in my PR - let me fix it and you can take another look.

**Comment by vsoch** [comment]
okay just pushed - take a look!

**Comment by depond1** [comment]
ok great! works perfectly

**Comment by vsoch** [comment]
Updated both end.sh and resume.sh, and merged! I'm going to close the issue since we've fixed the error, thanks for opening, and please ping again if you need help. :)
