### ISSUE TITLE
Exponential backoff

### ISSUE THREAD

**Issue by kcgthb** [vsoch/forward#5]
Hi @raphtown, 

Could I suggest to implement some sort of [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff) here:
https://github.com/drorlab/forward/blob/f6951a4c4ab8f2ed4fe711bbfef7ab1b36316051/start.sh#L48-L53
instead of querying the queue every second? That will likely be better for the scheduler for cases where the job is not dispatched right away.

Other than that, great job! And thanks for providing those scripts. They will certainly be of use to many users on Sherlock.

**Comment by vsoch** [comment]
@kcgthb this is a good idea, I'll do a PR and add the suggested change.

**Comment by raphtown** [comment]
Addressed by #8
